### ISSUE TITLE
(Question) Touchpad still disabled after typing stops, if touchpad sees input before typing stops

### ISSUE THREAD

**Issue by 0cv** [RedBearAK/toshy#404] opened 2024-09-20 10:40 UTC
I don't know if it's possible, and I know that this didn't work pre-install of Toshy so this is either me having missed some documentation in Toshy, or it's a missing feature altogether (which might not be fixable, let me know!)

While typing, the touchpad is disabled (and it's good). After typing it takes a fraction of a second for the touchpad to get activated again. If while "finishing" typing, I use the touchpad to move the cursor somewhere else, this action will be ignored **including after I stop typing** for as long as the finger is on the touchpad. Only if I release my finger from the touchpad and put it back on, then the cursor will start moving. Is it possible to fix this?

**Comment by RedBearAK** [comment] 2024-09-20 19:16
@0cv 

Given the nature of what the `libinput` feature is trying to accomplish (rejection of all mouse cursor movements and "clicks" that could normally be caused by resting the palm on the touchpad while typing), I would suspect that blocking touchpad input until the possible "palm" input is briefly removed from the touchpad after typing stops is a necessary way that the code would have to work. 

However, the only way to get a real answer to whether it could be tweaked in some way would be to query the `libinput` developers directly. That Wiki entry was provided by a Toshy user who found it useful, and I don't really know much more about it. All the keymapper behind Toshy really does is create a virtual keyboard device, which is why making that device get recognized as an "internal" keyboard sometimes helps the palm rejection feature of the desktop environment work correctly. 

I believe the active `libinput` repo is on GitLab: 

https://gitlab.freedesktop.org/libinput/libinput/-/issues

You could try something like this, but I still would have no answers for what the output would mean, or ways in which the device settings could be tweaked further: 

```
sudo libinput debug-events
```

**Comment by RedBearAK** [comment] 2024-09-23 02:57
Closing since there's nothing that Toshy could do about this internally.

**Closed by RedBearAK** 2024-09-23 02:57 UTC
Labels: question
