### ISSUE TITLE
[BUG] Xwayland window is not recognized with Sway

### ISSUE THREAD

**Issue by fmasa** [RedBearAK/toshy#131] opened 2023-12-29 15:18 UTC
```
Bare metal or virtual machine: bare metal

Linux distro name: arch 
Distro version: -
X11/Xorg or Wayland: wayland
Desktop environment(s):  sway

Any DE(s) tried with Wayland?: sway

Keyboard type (IBM, Chromebook, Windows, Apple): Windows
Keyboard device name (try 'toshy-devices'):  Logitech USB receiver (MX keys Mini)
```

Problem observed:  
* * *

When using Itellij IDEA (that is not Wayland-native and uses xwayland), the app class is not recognized.
This can be easily reproduced e.g. with `xeyes`:

![image](https://github.com/RedBearAK/toshy/assets/5658260/24a227be-4e8e-437a-a743-cf211f3433d1)

This is because on Wayland `app_id` is used instead of `WM_CLASS`, but maybe there could be a fallback to window class when `app_id` is not set?

See part of `swaymsg get_tree`:

```
        #49: con "xeyes" (xdg_shell, pid: 18298, app_id: "Alacritty")
        #50: con "xeyes" (xwayland, pid: 18398, instance: "xeyes", class: "XEyes", X11 window: 0x80000A)
```

**Comment by RedBearAK** [comment] 2023-12-29 23:09
@fmasa 

Well, that is kind of lame. I am not aware of having run into that in other desktop environments. Seems like I would have used at least one app during this past year that was running under XWayland, but maybe the solutions for other desktops are getting the window info in such a way that there is no difference. The sway solution is currently using the IPC calls, from what I remember. 

That code is in the development branch of my fork of `keyszer`, not directly in this project repo. I don't know exactly when I'll have time to get back into a sway VM and try to find a solution to this. 

```py
class Wl_sway_WindowContext(WindowContextProviderInterface):
    """Window context provider object for Wayland+sway environments"""

    def __init__(self):

        # Create the connection object
        self.cnxn_obj           = None
        self._establish_connection()

        self.wm_class           = None
        self.wm_name            = None

    @classmethod
    def get_supported_environments(cls):
        # This class supports the sway window manager environment on Wayland
        return [
            ('wayland', 'sway'),
            ('wayland', 'swaywm'),
        ]

    def _establish_connection(self):
        """Establish a connection to sway IPC via i3ipc. Retry indefinitely if unsuccessful."""
        while True:
            try:
                self.cnxn_obj = i3ipc.Connection(auto_reconnect=True)
                debug(f'CTX_SWAY: Connection object created.')
                break
            # i3ipc.Connection() class may return generic Exception, or ConnectionError
            except (ConnectionError, Exception) as cnxn_err:
                error(f'ERROR: Problem connecting to sway IPC via i3ipc:\n\t{cnxn_err}')
                time.sleep(3)

    def get_active_wdw_ctx_sway_ipc(self):
        """Get sway window context via i3ipc Python module methods."""
        try:
            tree                    = self.cnxn_obj.get_tree()
        except ConnectionResetError as cnxn_err:
            debug(f"IPC connection was reset (sway).\t\n{cnxn_err}")
            return NO_CONTEXT_WAS_ERROR
        focused_wdw             = tree.find_focused()
        if not focused_wdw:
            debug("No window is currently focused.")
            return NO_CONTEXT_WAS_ERROR
        self.wm_class           = focused_wdw.app_id or 'sway-ctx-error'
        self.wm_name            = focused_wdw.name or 'sway-ctx-error'
        return {"wm_class": self.wm_class, "wm_name": self.wm_name, "x_error": False}

    def get_window_context(self):
        """Return window context to KeyContext"""
        return self.get_active_wdw_ctx_sway_ipc()
```

I see what you're saying about maybe doing a fallback if the `app_id` is not set but the `name` attribute returns something. Might be do-able, but I've never attempted using the `Xlib` method to get window info in a Wayland environment. Or, most likely, the IPC calls will probably need to be used to test whether the app is in XWayland, and then pull the info with a different algorithm like from the sample you provided. 

```sh
        #50: con "xeyes" (xwayland, pid: 18398, instance: "xeyes", class: "XEyes", X11 window: 0x80000A)
```

**Comment by fmasa** [comment] 2023-12-30 00:22
@RedBearAK Thanks for the speedy response! (Also thanks for the whole Toshy - I was starting to go crazy when switching between company-issued Macbook and my personal Linux workstation and Toshy was exactly the kind of solution that fixed almost everything!)

>>> I see what you're saying about maybe doing a fallback if the app_id is not set but the name attribute returns something. Might be do-able, but I've never attempted using the Xlib method to get window info in a Wayland environment. Or, most likely, the IPC calls will probably need to be used to test whether the app is in XWayland, and then pull the info with a different algorithm like from the sample you provided.

i3ipc actually exposes the wm_class as well, so the fallback can be implemented as:

```diff
- self.wm_class           = focused_wdw.app_id or 'sway-ctx-error'
+ self.wm_class           = focused_wdw.app_id or focused_wdw.window_class or 'sway-ctx-error'
```

I tested it locally and it works as expected:

![image](https://github.com/RedBearAK/toshy/assets/5658260/b8893071-76a0-4c00-b9b9-53091ae33775)

I can submit PR against the fork if you want.

**Comment by RedBearAK** [comment] 2023-12-30 00:29
Oh, wow, that does look nice and simple. Let me just slip that into the branch and you can test it by reinstalling Toshy. I'll let you know when the change should be live. 

Since this is a change to the `keyszer` branch it would not be necessary to download a new zip of Toshy. The same Toshy installer will just re-clone the `keyszer` branch and set up a new Python virtual environment, and make a backup of your config file, while re-integrating any changes you've made to the config if they are in the editable marked "slices".

**Comment by RedBearAK** [comment] 2023-12-30 00:36
Should be ready to do a re-install test now. From the same `setup_toshy.py` you've already downloaded and used. 

If you're feeling adventuresome you could download the `dev_beta` branch zip of Toshy and verify that I haven't messed anything up by adding support for Void Linux. There should be nothing in the new changes in Toshy that would make any difference to your use case either way, and it would also do the fresh clone of the `keyszer` branch. 

Let me know either way.

**Comment by RedBearAK** [comment] 2023-12-30 00:44
Let me know also if you need some assistance doing some custom overrides of certain shortcuts like Cmd+Space. I can't really have a rational set of defaults for sway due to how it's often set up manually. Best place to set up some overrides is in the "User Apps" slice of the config file, if you want to keep your sway shortcuts set to the distro defaults so they stay the same as they were before when Toshy is disabled/off. 

I think there is already a keymap matching on "sway" so there is an example to work from, but if you edit that one outside of an editable set of slice markers, that will get overwritten by the default contents of the config file whenever you run the installer again.

**Comment by RedBearAK** [comment] 2023-12-30 00:53
It doesn't appear to be an issue right now, but I wonder if there is any reason to also have a fallback for the `window_title` attribute. Maybe I should just put that in place as a comment in case something comes up. But it doesn't immediately appear to be necessary or useful to have that active... 

```py
        self.wm_name            = focused_wdw.name or 'sway-ctx-error'
        # self.wm_name            = focused_wdw.name or focused_wdw.window_title or 'sway-ctx-error'
```

**Comment by RedBearAK** [comment] 2023-12-31 03:09
@fmasa 

Had some time to get into the Fedora Sway VM and test the update with `xeyes`. Seems to be working fine. 

Can you confirm this fixes your issue with IntelliJ IDEA?

**Comment by fmasa** [comment] 2023-12-31 16:19
@RedBearAK I can confirm that it now works as expected :+1: 

Thank you very much!

> But it doesn't immediately appear to be necessary or useful to have that active...

I tried this with a few apps and for me `name` is always set for both wayland and xwayland apps to correct title, while `window_title` is  `None` for wayland apps and correct window title for xwayland apps. So I don't think the fallback is necessary there.

> Let me know also if you need some assistance doing some custom overrides of certain shortcuts like Cmd+Space. 

Thanks! I think I got this figured out :slightly_smiling_face: and I use fairly non-standard shortcuts for sway & macos window management anyway :see_no_evil: and I think this will be the case with many sway users :man_shrugging: 

> If you're feeling adventuresome you could download the dev_beta branch zip of Toshy and verify that I haven't messed anything up by adding support for Void Linux.

I'll give it a shot!

**Comment by RedBearAK** [comment] 2023-12-31 23:45
@fmasa 

Thanks for the feedback. 

> I tried this with a few apps and for me name is always set for both wayland and xwayland apps to correct title, while window_title is None for wayland apps and correct window title for xwayland apps. So I don't think the fallback is necessary there.

Good. That means putting the fallback in place should work, but is apparently pointless and unnecessary. So I'll leave it out. Makes you wonder why the app class isn't also pulled through for XWayland apps in the same way. 

The changes for installing on Void Linux were already merged into the main branch, so it shouldn't have made any difference at this point. But the `dev_beta` often has new stuff in testing (that often briefly breaks things), so stick with the main branch from now on if you need to re-install somewhere. 👍🏽 

Since I merged the Void Linux changes and you've confirmed that the elegant fix you provided for this Sway issue is working, I'm going to consider this resolved. Please feel free to open new issues. 

> Thanks! I think I got this figured out 🙂 and I use fairly non-standard shortcuts for sway & macos window management anyway 🙈 and I think this will be the case with many sway users 🤷‍♂️

I figured that might be the case with something like sway. Just maintain awareness that if you're modifying the config file outside the marked "slices" you may have to re-merge those changes manually from the backup folder the installer creates. They should be in the most recent folder inside the folder named like this: `~/.config/toshy_config_backups`. There's no Python `venv` inside the backup folders so they are fairly small. 

Maybe at some point the config file can migrate into a more "declarative" format that will be easier to maintain and upgrade, but this is the best I could do for now. 

Thanks for the fix! ❤️

**Comment by RedBearAK** [comment] 2023-12-31 23:45
Closing as resolved.

**Closed by RedBearAK** 2023-12-31 23:45 UTC
Labels: bug
