### ISSUE TITLE
(Enh) Void Linux / Runit support

### ISSUE THREAD

**Issue by NotAlexNoyle** [RedBearAK/toshy#129] opened 2023-12-28 22:49 UTC
I recently discovered toshy after revisiting kinto to see if it worked on non-systemd init systems. When I run it, I get:

> (EE) ERROR: Installer does not know how to handle distro: "void"

I am running void linux with KDE Plasma on wayland. It would be great if you could add support for my system. I miss my mac keybindings. Thank you.

**Comment by RedBearAK** [comment] 2023-12-28 23:43
@NotAlexNoyle 

Indeed, that would be great. The installer script is somewhat modular, at least as far as the installation of a necessary list of native packages is concerned. So in theory a new set of package manager logic can be assembled and a package list suitable for Void could be put together. 

The logic around what to do without `systemd` being available is more simplistic at the moment. But the installer is set up to just avoid the `systemd` stuff if `systemd` is not the init system, and there is a way to run just the keymapper config process with a "manual" command that could be run at startup if you want, and that manual config script can be managed either from the terminal or from the tray icon menu (if the tray icon will work in your desktop environment). 

The service units on a `systemd` system allow Toshy to have some multi-user features that can't really be replicated using other init systems, but that really isn't important in probably 95% of cases. So I probably won't even attempt to create scripts for Runit, just like I didn't for SysVinit. It isn't really necessary. 

Void is an independent distro, so not closely related enough that you could try the `--override-distro` option. But I managed Solus without too much trouble, which is another independent distro not based on anything else. 

I'll have to download an ISO and try to set up a VM for figuring out the package names and how to use the package manager commands and options. Could take some time. 

I have no idea right now whether it will have any impact at all, but are you using the `glibc` or `musl` variant of Void? Which image did you install from, and what is your desktop environment? I'd like to start testing with something close to what you have.

**Comment by NotAlexNoyle** [comment] 2023-12-28 23:54
> there is a way to run just the keymapper config process with a "manual" command that could be run at startup if you want, and that manual config script can be managed either from the terminal or from the tray icon menu (if the tray icon will work in your desktop environment).

That works for me, is this process documented? runit services are basically just sh scripts.

> I'll have to download an ISO and try to set up a VM for figuring out the package names and how to use the package manager commands and options. Could take some time.

To search you can use xbps-query -Rs <name>

> I have no idea right now whether it will have any impact at all, but are you using the `glibc` or `musl` variant of Void? Which image did you install from, and what is your desktop environment? I'd like to start testing with something close to what you have.

I installed void using [this guide](https://docs.zfsbootmenu.org/en/v2.2.x/guides/void-linux/uefi.html). I am using glibc, KDE Plasma, and Wayland.

**Comment by RedBearAK** [comment] 2023-12-29 00:13
@NotAlexNoyle 

> That works for me, is this process documented? runit services are basically just sh scripts.

Yes, most of the init systems other than `systemd` are relatively simplistic by comparison, and shell script based. Which, although it can be a bit gnarly to get working, I think the additional power and configurability is why `systemd` has kind of "won" the battle of which init to use on most distros. 

You can literally just open a terminal whenever you log in and run this command, or find some other way to run it automatically if you feel that's important: 

```
toshy-config-start
```

There is the verbose debugging command, which is extremely useful for seeing what is going on (or going wrong): 

```
toshy-config-verbose-start
```

The commands are scripts designed to make it easy to switch between verbose and normal manual operation, or running from the `systemd` services, without worrying about trying to find an kill any existing process. So you may see some irrelevant output as each script tries to shut down any blocking process. 

The start script should run the config in the background, then it can be stopped either from the tray icon or with: 

```
toshy-config-stop
```

One minor thing to be aware of is that if you change your default shell or somehow manage to reset your shell RC file and your distro doesn't automatically put your `~/.local/bin` folder in the PATH, you may need to re-run this script to regain easy access to these commands: 

```
~/.config/toshy/scripts/toshy-bincommands-setup.sh
```

And then follow the instructions to open a new terminal or at least "source" your shell RC file again, to fix the PATH variable. 

>  I am using glibc, KDE Plasma, and Wayland.

OK, I think I'll just start with the Xfce ISO (glibc) and then attempt a Plasma install only if you have a problem. Once I get past the native packages stage the DE (since it's one of the few Wayland environments that is already well-supported) should just work. Infamous last words. 

I could be done with this by tomorrow, or it could take several days, depending on how involved it is to find the new list of packages and overcome unforeseen glitches. I've never worked with Void before. 

If you are feeling so inclined and have a lot of time on your hands, you can try to match these existing lists with package names you find by searching in Void: 

https://github.com/RedBearAK/toshy/blob/b8603725760c4151fa76bf97626fba3269b11460/setup_toshy.py#L417-L533

**Comment by RedBearAK** [comment] 2023-12-29 07:07
Here's a preliminary package list I've verified with the online Void package database. The ISO is taking forever to download, and I have some other stuff to do, so I'm not sure when I'll be able to test this myself. 

```py
    'void-based':          ["cairo-devel", 
                            "dbus-devel",
                            "evtest",
                            "gcc", "git",
                            "libayatana-appindicator-devel", "libgirepository-devel", "libnotify",
                            "python3-dbus", "python3-devel", "python3-pip", "python3-tkinter",
                            "wayland-devel",
                            "xset",
                            "zenity"],
```

This and the package manager command logic are in the `dev_beta` branch. If you switch to the branch on the main page and download a new zip, this could already work, in theory. Or, there might still be an additional package or two necessary to solve a problem during the Python virtual environment install phase. 

Can't promise anything, but feel free to make the attempt.

**Comment by NotAlexNoyle** [comment] 2023-12-29 20:37
The installation worked, and I have the tray icon. But the "Re/Start Toshy Script" does not seem to enable the program for me. I get a banner notification that says something about systemd services, and the preferences panel reads:

Toshy Config: Unknown

Session Monitor: Unknown

**Comment by RedBearAK** [comment] 2023-12-29 21:33
The tray menu saying "Unknown" for the services is normal, since there is no `systemd`, so those services don't exist. That doesn't hurt anything. 

On the other hand, there should be no notification when using the "Script" items, as far as I know. That should only happen if you picked one of the "Services" items on the menu. (I know, it's not the clearest naming for everything.)

Do you recall exactly how you installed your KDE Plasma desktop? Will the "kde5" or "plasma-desktop" packages get it all working? The "kde5" package says it's a meta-package. I'll have to double-check that the complicated Wayland+Plasma solution actually works without any `systemd` involved. 

Meanwhile, you should try the verbose command in a terminal and see how it goes.

**Comment by NotAlexNoyle** [comment] 2023-12-29 21:55
> Do you recall exactly how you installed your KDE Plasma desktop? Will the "kde5" or "plasma-desktop" packages get it all working? The "kde5" package says it's a meta-package.

kde5 is the right package, you just have to install it and enable the services with a symlink like in [this guide](https://xfano.github.io/posts/void-linux-installing-kde-plasma-desktop/).

> Meanwhile, you should try the verbose command in a terminal and see how it goes.

Starting it manually works! I guess its only the tray/preferences GUI that doesn't work.

**Comment by NotAlexNoyle** [comment] 2023-12-29 21:59
Actually, it is all working now. I just have to start the script manually one time, and then the "Re/Start Toshy Script" option in the menu works, and the background process takes over. Thank you!

**Comment by RedBearAK** [comment] 2023-12-29 22:21
Be sure that it is really working. One of the quickest ways to know is if `Cmd+comma` brings up the settings in Firefox by opening a new tab and typing the macro "about:preferences[Enter]". If that doesn't work, it isn't completely working. 

A lot of basic shortcuts will seem to work just by it getting to the level of moving modifier keys. 

Another good test is opening a terminal and using Cmd+T to open a couple of new tabs. Then see if Shift+Cmd+Left/Right (arrow keys) will do tab navigation. If Shift+Cmd+Left_Brace/Right_Brace (the bracket keys) works for tab navigation, but the arrow keys don't, that can be a sign that the terminal is not being recognized as a terminal. 

Also, I guess earlier in that process you shouldn't even be able to open a new terminal tab with Cmd+T if it isn't being recognized as a terminal app. That should require Shift+Cmd+T, and Shift+Cmd+W to close the tab, if the app-specific remapping is not working. 

I'm getting an `elogind` loop at the login screen, so I haven't been able to test KDE just yet.

**Comment by NotAlexNoyle** [comment] 2023-12-29 22:32
> Be sure that it is really working. 

All of the things you suggested to try are working.

> I'm getting an `elogind` loop at the login screen, so I haven't been able to test KDE just yet.

Try disabling the elogind runit service. If you already enabled dbus you might not need it.

**Comment by NotAlexNoyle** [comment] 2023-12-29 22:34
I can't seem to switch tabs in my browser the way that I can in the terminal, not sure if that is intended behavior or not.

**Comment by RedBearAK** [comment] 2023-12-29 22:52
> Try disabling the elogind runit service. If you already enabled dbus you might not need it.

I followed some instructions to supposedly do that, but ended up with a black screen with a cursor in the top left doing Morse code at me instead of a login screen. May have to reset the VM to the last snapshot and try the Plasma setup again. 

Anyway, sounds like things are working as intended. The arrows tab navigation is something I copied from the terminal in macOS, but the Shift+Cmd+Braces shortcut is applied to all GUI apps (and terminals). 

Another good diagnostic tool is Shift+Opt+Cmd+I,I (double-tap the "I" key quickly while holding the modifiers). That should bring up a `zenity` info dialog window that shows the app class, window title and keyboard device info at the moment you triggered the shortcut. If that seems to show the correct info for any app that is not a "remote desktop" or some kind of virtual machine app (where the keymapping is supposed to get automatically disabled) then you should be golden. 

You will of course run into some ways in which this is not like being on macOS, there are a lot of limitations. Sometimes we can fix that, other times not. 

If you aren't going to install `ibus` and choose it as your input manager, the Option-key special characters won't work correctly except in GTK apps, so if you don't care about the special characters you may wish to disable the special character layout in the "OptSpec Layout" sub-menu in the tray icon menu. 

Other than that, enjoy, and do your best to find problems and don't feel bad about reporting them. But scan through the FAQ entries on the main page/README, especially the "suspend" thing talking about throttle delays. Many users need to tweak that to enable Cmd+Click and Shift+Click kinds of actions without waiting a full second before clicking.

**Comment by NotAlexNoyle** [comment] 2023-12-29 23:03
The zenity shortcut works also. I am already using ibus so the option key special characters work fine. Is there any way to whitelist an application? I am concerned it could create a slight input delay in FPS games.

**Comment by RedBearAK** [comment] 2023-12-29 23:26
> The zenity shortcut works also. I am already using ibus so the option key special characters work fine.

Nice. 

>  Is there any way to whitelist an application? I am concerned it could create a slight input delay in FPS games.

Yeah, it could. Toshy is definitely a bit "heavier" than Kinto was, and it has that default throttle delay to make macros work. 

Well, as mentioned earlier anything in the "remotes" list in the config causes the keymapper to... not "stop" exactly but to simply cease modmapping and keymapping activities, and just become a pass-thru device as long as that app class is detected. Whether that completely stops the default throttle delays from being applied to modifier key presses... I think so? But technically the config is still being evaluated in some sense on each key press. 

You could try putting your games' app class(es) in the "remotes" list, and see how well that works out. (You need to restart the keymapper process if you modify the config file.) But, the "remotes" list is not in a part of the config file that is designed to retain user changes, so if you re-ran the installer to get new features/fixes you'd have to restore that change from the config file backup the installer creates. Not something you are likely to do more than a couple of times a year, if at all, but just something to be aware of. I have improved the upgrade process over Kinto, but it's still awkward depending on what you do to the config file. 

The other option of course is just to stop the keymapper process/script from the tray icon anytime you want to play a game. It takes about 5 seconds to restart the keymapper when you choose the "start script" option. 

If you want to try adding the app class to the remotes list, look for this: 

```py
remotes_lod = [
    {clas:"^Gnome-boxes$"                },
    {clas:"^org.remmina.Remmina$", not_name:"^Remmina Remote Desktop Client$|^Remote Connection Profile$"},
    {clas:"^Nxplayer.bin$"               },
    {clas:"^remmina$"                    },
    {clas:"^qemu-system-.*$"             },
    {clas:"^qemu$"                       },
    {clas:"^Spicy$"                      },
    {clas:"^Virt-manager$"               },
    {clas:"^VirtualBox$"                 },
    {clas:"^VirtualBox Machine$"         },
    {clas:"^xfreerdp$"                   },
    {clas:"^Wfica$"                      },
]
```

If you have a single "app" that runs your games, you might be able to just add that app class (like "steam", maybe?) to the list and restart the keymapper, and all the usual effects of the keymapper should disappear whenever you are in one of the games. Until you do that, the diagnostic dialog would help with identifying the app class. Afterwards, I think the dialog would stop appearing. 

So if your app class is "Steam" (the matching is case-insensitive unless you force it to be case-sensitive), you'd add it like this: 

```py
remotes_lod = [
    {clas:"^Gnome-boxes$"                },
    {clas:"^org.remmina.Remmina$", not_name:"^Remmina Remote Desktop Client$|^Remote Connection Profile$"},
    {clas:"^Nxplayer.bin$"               },
    {clas:"^remmina$"                    },
    {clas:"^qemu-system-.*$"             },
    {clas:"^qemu$"                       },
    {clas:"^Spicy$"                      },
    {clas:"^Steam$"},
    {clas:"^Virt-manager$"               },
    {clas:"^VirtualBox$"                 },
    {clas:"^VirtualBox Machine$"         },
    {clas:"^xfreerdp$"                   },
    {clas:"^Wfica$"                      },
]
```

And then stop and start the config script again.

**Comment by RedBearAK** [comment] 2023-12-30 04:16
@NotAlexNoyle 

I finally fought my way through some instability with the VM software and just stuck with the Xfce login manager instead of trying to enable SDDM, and got a working Wayland+KDE session. Not seeing any issue when starting the manual script option from the tray icon menu, even without running the terminal command first. (The tray icon item literally runs the same terminal command, just in the background.)

I didn't point it out before, but on Wayland+KDE there will always be a little dialog that pops up and then disappears automatically after 1 second. This forcibly fixes a weird issue where the KWin script that grabs the focused app window info can have no info available until some kind of KWin "event" happens, like switching the focused app window. It's mostly harmless but can cause a switch of which window has the keyboard focus. You should see that dialog briefly every time you start or restart the keymapper process in Wayland+KDE. 

Wayland+KDE was complicated to get working. I tell you what. 

I'll be closing this out soon, after I merge the changes with the main branch, unless you can point to a problem with the general Void support we implemented here. But it seems pretty solid now. 

As mentioned before, there's not much benefit to doing non-systemd service scripts. So I consider this done as long as it installs smoothly on Void. It's a manual startup situation, just like CentOS and antiX, and MX Linux if you're booting with SysVinit. 

Thanks for the request and the help with testing. 👍🏽

**Comment by NotAlexNoyle** [comment] 2023-12-30 04:41
That’s fine by me, void users are capable of setting up their own services. I’m satisfied with the degree of support. Thanks again.

**Comment by RedBearAK** [comment] 2023-12-30 10:40
@NotAlexNoyle 

Merged into main, put some notes about Void in the README. 

Thanks again for your interest in running Toshy on something new, and confirming that it is working. 

Closing as completed.

**Closed by RedBearAK** 2023-12-30 10:40 UTC
Labels: enhancement

**Comment by RedBearAK** [comment] 2023-12-31 02:54
Welp. Tried doing an announcement on the Void Linux subreddit, but even though they literally have no rules posted the mods declared it to be off topic after it was up for a couple of hours. So, I guess Void users will have to find their own way to the Toshy club. 😆
