### ISSUE TITLE
(Question) How does a modmap change a keymap? 

### ISSUE THREAD

**Issue by keithbentrup** [RedBearAK/toshy#408] opened 2024-09-29 17:20 UTC
First, thanks so much for this project!! It's made my transition to the Linux Desktop much easier.

One hangup that I have is trying to map my OSX tiling shortcuts (adopted from [ShiftIt](https://github.com/fikovnik/ShiftIt)).
![Screenshot Menu](https://raw.github.com/fikovnik/ShiftIt/develop/docs/schreenshot-menu.png)

It works as expected using the gnome extension [Tiling Assistant](https://github.com/Leleat/Tiling-Assistant) for all applications except terminal emulators. The `"Super-C-Alt-[Right|Left|Up|Down]"` simply does not respond.
 
From what I can work out, it's because of this [modmap](https://github.com/RedBearAK/toshy/blob/b103c5de50cc10c39384767d62333ba820209962/default-toshy-config/toshy_config.py#L1645) for terminals using a windows keyboard, but I can't figure out how I'm supposed to override this in my `user_apps` section.

```python
modmap("Cond modmap - Terms - Win kbd", {
    # - Default Mac/Win
    # - Default Win
    Key.LEFT_CTRL:              Key.LEFT_CTRL,                  # WinMac
    Key.LEFT_META:              Key.LEFT_ALT,                   # WinMac
    Key.LEFT_ALT:               Key.RIGHT_CTRL,                 # WinMac
}, when = lambda ctx:
    isKBtype('Windows', map='mmap terms Win')(ctx) and
    matchProps(clas=termStr)(ctx)
)
```
 
 I've tried many variations, but nothing quite works. Any guidance or other ideas?
 
 ```python
 # from my user_apps section
 keymap("My Term Overrides", {
    # ??? what goes here
    C("???-Right"):             [iEF2NT(),C("Super-C-Alt-Right")],
    C("???-Left"):             [iEF2NT(),C("Super-C-Alt-Left")],
    ...
}, when = lambda ctx:
    cnfg.screen_has_focus and
    matchProps(clas=termStr)(ctx)
)
```

**Comment by RedBearAK** [comment] 2024-09-29 18:35
@keithbentrup 

Nice work getting to this level of understanding. Now try this in place of your “???” placeholder. 

```
LC-Alt-RC
```

There’s no `Meta/Super/Win` key in terminals so it becomes `LC` whereas the virtualized Command key is `RC` throughout the config file. 

The order of the modifiers doesn’t particularly matter, but I put them in the same order as the macOS screenshot. Which also happens to be left-to-right. After the modmapping. 

There should be no need to change anything about the “output” shortcuts from your example. Looks good. 

Let me know if this doesn’t work out.

**Comment by keithbentrup** [comment] 2024-09-29 22:34
Hi @RedBearAK, thanks for the quick response. 

I had tried that combo first because that's how I interpreted the code. It didn't work, and I didn't understand why. After your response, reviewing the docs again, and looking at some of my other modifications, it was because I had changed the [suspend timeout to 0.1 so that I could option click on links in vscode](https://github.com/RedBearAK/toshy/wiki/FAQ-(Frequently-Asked-Questions)#modclicking-blocked-by-keymapper-suspend-timeout).

This had the unfortunate side effect that I had a tiny amount of time to hit 3 keys with my my left hand, so it didn't appear to work, so now I adjusted the timeout back. I have a slight delay before I can option click links in vscode, but my shortcuts work. :tada:

**Comment by RedBearAK** [comment] 2024-09-30 00:19
>  It didn't work... because I had changed the suspend timeout to 0.1

Well that's unfortunate, if true. But I don't see how that could be the cause of these shortcuts not working. 

The "diagnostic dialog" shortcut is `Shift+Opt+Cmd+I,I` (with the "I" being double-tapped). This works even if I take significant time between pressing the modifiers. 

If anything this may be due to the keymapper by default being set up to ignore "repeat" key events, which can cause a remapped shortcut to revert to what it would be prior to remapping. But... yeah, I'm confused. That shouldn't have any effect on this. 

I made a new shortcut that doesn't use `isDoubleTap()` and deliberately waited between each modifier until each one was repeating (using `toshy-debug` in the terminal to see the debugging output), but the shortcut still activated the diagnostic dialog each time. So I'm really not sure what you've got going on there. 

Even tried making it `LC-Alt-RC` and using it in the terminal. Still works, regardless of any delayed key pressing. 

```py
keymap("Diagnostics", {
    C("Shift-Alt-RC-i"):        isDoubleTap(notify_context),
    C("Shift-Alt-RC-t"):        isDoubleTap(macro_tester),
    C("LC-Alt-RC-x"):        notify_context,

}, when = lambda ctx: ctx is ctx )
```

Or even adding the function call that resets the Enter key state. So that's not the problem. 

```py
keymap("Diagnostics", {
    C("Shift-Alt-RC-i"):        isDoubleTap(notify_context),
    C("Shift-Alt-RC-t"):        isDoubleTap(macro_tester),
    C("LC-Alt-RC-x"):           [iEF2NT(), notify_context],
}, when = lambda ctx: ctx is ctx )
```

Maybe you were having trouble because the shortcut was activating a shell extension? But even that doesn't make much sense to me. If the keymapper recognizes the input keys and triggers the correct output shortcut on the virtual keyboard, that should be that. The shortcuts should have "just worked" the whole time. 

You can try this in your `keymapper_api` slice, along with pushing the suspend timer back down to 0.1, but it shouldn't make any difference to anything, except repeating keys will use some additional CPU (not the best for gaming, but also fixes the emacs "wordwise" shortcuts). 

```py
ignore_repeating_keys(False)
```

I'm really curious what the actual problem is here.

**Comment by keithbentrup** [comment] 2024-09-30 01:51
Huh ... that is weird.

Here's a diff of my current config that behaves as I described. I removed all other changes. I have to be very fast to tile the terminal window (tried gnome terminal and xterm), but I can do it typically with multiple attempts. The "diagnostic dialog" shortcut worked as you described, and timing did not seem to be an issue in terminal windows (i.e. seems unaffected by the 0.1 suspend timeout). 

 
```diff
46c46
<     suspend             = 1,        # default: 1 sec, try 0.1 sec for touchpads/trackpads
---
>     suspend             = 0.1,        # default: 1 sec, try 0.1 sec for touchpads/trackpads
3262a3263,3274
> )
> 
> keymap("My Term Overrides", {
>     C("LC-Alt-RC-Right"):             [iEF2NT(),C("Super-C-Alt-Right")],
>     C("LC-Alt-RC-Left"):             [iEF2NT(),C("Super-C-Alt-Left")],
>     C("LC-Alt-RC-Up"):             [iEF2NT(),C("Super-C-Alt-Up")],
>     C("LC-Alt-RC-Down"):             [iEF2NT(),C("Super-C-Alt-Down")],
>     C("LC-Alt-RC-m"):             [iEF2NT(),C("Super-C-Alt-m")],
>     C("LC-Alt-RC-x"):           [iEF2NT(), notify_context],
> }, when = lambda ctx:
>     cnfg.screen_has_focus and
>     matchProps(clas=termStr)(ctx)
```

If I revert that suspend timeout, I can easy tile the terminals, and I'm unaware of any other modifications to my system that might be interfering.

Also, I tried to eliminate the shell extension interference as a possibility as you mentioned. I added `C("LC-Alt-RC-c"):             [iEF2NT(),C("C-c")],` to the list to trigger a Ctrl-c in the terminal. This IS affected by the suspend timeout value (i.e. I have to be fast with low values for the suspend timeout). Does that add any insight or just make it more confusing?

I'm okay with just having a short delay to clicking in vscode, but if you want me to test something for completeness, happy to help.

**Comment by RedBearAK** [comment] 2024-09-30 02:52
I tried your `Ctrl+C` example and got an exception in the debugging output that I've never seen before. Do you see anything like this with these failing shortcuts, when using `toshy-debug`? 

```
(DD) WM_CLASS: 'org.kde.konsole' | WM_NAME: 'Downloads : bash — Konsole'
(DD) DEVICE: 'AT Translated Set 2 keyboard' | CAPS_LOCK: 'False' | NUM_LOCK: 'False'
(DD) ACTIVE KEYMAPS:
     'User hardware keys', 'Currency character overlay', 'User overrides: KDE',
     'Testing Hyper modifier', 'Wordwise - not vscode', 'Konsole tab switching',
     'Konsole terminal - not tab nav', 'GenTerms overrides: Ubuntu/Fedora',
     'GenTerms overrides: KDE', 'General Terminals', 'GenGUI overrides: not
      … Chromebook', 'GenGUI overrides: KDE', 'General GUI', 'Diagnostics'
(DD) COMBO: VLCtrl-VLOpt-VCmd-C => [<function iEF2.<locals>._is_Enter_F2 at 0x7f7f02ebef20>, Ctrl-C] in KMAP: 'User hardware keys'
(DD) spent modifiers []
(DD) _is_Enter_F2:  combo_list      = [None]
(DD) _is_Enter_F2:  _enter_is_F2    = True
Exception in callback receive_input(InputDevice('...input/event4')) at /home/kris/.config/toshy/.venv/lib64/python3.12/site-packages/xwaykeyz/input.py:105
handle: <Handle receive_input(InputDevice('...input/event4')) at /home/kris/.config/toshy/.venv/lib64/python3.12/site-packages/xwaykeyz/input.py:105>
Traceback (most recent call last):
  File "/usr/lib64/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/kris/.config/toshy/.venv/lib64/python3.12/site-packages/xwaykeyz/input.py", line 120, in receive_input
    on_event(event, device)
  File "/home/kris/.config/toshy/.venv/lib64/python3.12/site-packages/xwaykeyz/transform.py", line 389, in on_event
    on_key(ks, context)
  File "/home/kris/.config/toshy/.venv/lib64/python3.12/site-packages/xwaykeyz/transform.py", line 469, in on_key
    transform_key(key, action, context)
  File "/home/kris/.config/toshy/.venv/lib64/python3.12/site-packages/xwaykeyz/transform.py", line 516, in transform_key
    reset_mode = handle_commands(keymap[combo], key, action, ctx, combo)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kris/.config/toshy/.venv/lib64/python3.12/site-packages/xwaykeyz/transform.py", line 614, in handle_commands
    _output.send_combo(command)
  File "/home/kris/.config/toshy/.venv/lib64/python3.12/site-packages/xwaykeyz/output.py", line 142, in send_combo
    mods_we_need_to_press.remove(modifier)
  File "<frozen _collections_abc>", line 729, in remove
KeyError: Ctrl<Key.LEFT_CTRL>
```

I'm not immediately sure what's happening here. But it looks like you managed to find a bug with this particular type of shortcut.

**Comment by RedBearAK** [comment] 2024-09-30 06:15
It seems a possible mitigation for this, without even changing any code in the keymapper, is to differentiate between `LC` and `RC` on the output combo side of the remaps. This is something that is usually a good idea to avoid in the output combos, although it is highly useful on the input side of the mappings, as you've seen. 

I don't think it matters whether you go for `LC` or `RC`. Most applications don't care which one you press, except in rare instances like the GNOME `overlay-key` shortcut, which is hard-coded in the shell to only accept either the left or right Super key. 

This should do no harm, but should allow the shortcuts to work without being affected by the suspend timer value. 

```py
    C("LC-Alt-RC-c"):               C("LC-c"),
```

Or...

```py
    C("LC-Alt-RC-c"):               C("RC-c"),
```

I need to keep trying to fix the COSMIC context method that got broken by a Wayland protocol update, but when I have more time I'll try to get to the heart of whatever is going wrong here. 

I think normally when you put a "C" in the output combo, it will be `LEFT_CTRL`, so it's pretty funny that `LC` will fix the problem just as easily as `RC`. But I suspect that a list of modifier aliases is being populated by only a single undifferentiated `Ctrl` alias, which then gets removed prematurely because both `LCtrl` and `RCtrl` are in the input modifiers that are being "suspended" and resumed. That would explain why this only seems to happen when a combo uses both `LC` and `RC` together.

**Comment by keithbentrup** [comment] 2024-09-30 14:24
When I used `toshy-debug`, I got the same types of errors for each of the shortcuts impacted by the suspension timeout, and using `LC` resolved the immediate issue without error and allowed me to have the lower timeout. Thanks!

It's an interesting edge case -- probably very rare for keyboard shortcuts to "use" (b/c of the modmap) both ctrls.

It seems like you have a handle on the underlying cause, but there's also a simple workaround for now, too. 

Thanks again for your help and the great project!

**Comment by RedBearAK** [comment] 2024-11-21 04:20
I went ahead and implemented a simple fix in the keymapper to prevent the `KeyError` exception with this edge case. It's probably not the most perfect solution but I think it should be adequate for all the real-world use cases. 

If anyone were to freshly install or reinstall Toshy from a new zip file right now, they should end up with `xwaykeyz` tagged as version 1.3.3 or later, which will have this fix. (You may need to restart the services again to see the new version number in the services log, if you are upgrading from an earlier version.)

I'm going to close this as resolved. Using both left and right variants of the same modifier in an input combo should no longer cause a problem when the generic form of the modifier also exists in the output combo. The problem was a redundant attempt to remove a pressed modifier that had already been removed in a previous pass of a `for` loop. 

If anyone still has this issue or just wants to leave a confirmation that the fix works, leave me an "@" here. 

Have a decent Thanksgiving. 🦃  🍷

**Closed by RedBearAK** 2024-11-21 04:20 UTC
Labels: question
