### ISSUE TITLE
[BUG] Caps lock behavior after sleep. 

### ISSUE THREAD

**Issue by amrit92** [RedBearAK/toshy#281] opened 2024-05-29 14:59 UTC
```
Bare metal or virtual machine: 
(If in VM, which VM software): None

(Try running 'toshy-env' in a terminal to fill out the following fields...)

Linux distro name: Manjaro Linux on Wayland with latest  Gnome
Distro version: 
Distro variant: 
X11/Xorg or Wayland: 
Desktop environment(s): 
DE version(s): 

Keyboard type (IBM, Chromebook, Windows, Apple): 
Keyboard device name (try 'toshy-devices'): 
Targus dual mac/win keyboard
```

Showing systemd journal messages for Toshy services (since last boot):
May 29 07:54:53 ser-pc bash[3694]:         (Ignore this error if screen was locked/inactive at the time.)
May 29 07:54:53 ser-pc bash[3694]:         These shell extensions are compatible with keyszer:
May 29 07:54:53 ser-pc bash[3694]:             xremap@k0kubun.com (supports pre-GNOME 41.x):
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/5060/xremap/)
May 29 07:54:53 ser-pc bash[3694]:             window-calls-extended@hseliger.eu:
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/4974/window-calls-extended/)
May 29 07:54:53 ser-pc bash[3694]:             focused-window-dbus@flexagoon.com:
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/5592/focused-window-d-bus/)
May 29 07:54:53 ser-pc bash[3694]: (EE) Install "Extension Manager" from Flathub to manage GNOME Shell extensions
May 29 07:54:53 ser-pc bash[3694]: (EE) ############################################################################
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'xremap@k0kubun.com':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/com/k0kubun/Xremap”
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'window-calls-extended@hseliger.eu':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/org/gnome/Shell/Extensions/WindowsExt”
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'focused-window-dbus@flexagoon.com':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/org/gnome/shell/extensions/FocusedWindow”
May 29 07:54:53 ser-pc bash[3694]: (EE) ############################################################################
May 29 07:54:53 ser-pc bash[3694]: (EE) SHELL_EXT: No compatible GNOME Shell extension responding via D-Bus.
May 29 07:54:53 ser-pc bash[3694]:         (Ignore this error if screen was locked/inactive at the time.)
May 29 07:54:53 ser-pc bash[3694]:         These shell extensions are compatible with keyszer:
May 29 07:54:53 ser-pc bash[3694]:             xremap@k0kubun.com (supports pre-GNOME 41.x):
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/5060/xremap/)
May 29 07:54:53 ser-pc bash[3694]:             window-calls-extended@hseliger.eu:
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/4974/window-calls-extended/)
May 29 07:54:53 ser-pc bash[3694]:             focused-window-dbus@flexagoon.com:
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/5592/focused-window-d-bus/)
May 29 07:54:53 ser-pc bash[3694]: (EE) Install "Extension Manager" from Flathub to manage GNOME Shell extensions
May 29 07:54:53 ser-pc bash[3694]: (EE) ############################################################################
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'xremap@k0kubun.com':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/com/k0kubun/Xremap”
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'window-calls-extended@hseliger.eu':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/org/gnome/Shell/Extensions/WindowsExt”
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'focused-window-dbus@flexagoon.com':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/org/gnome/shell/extensions/FocusedWindow”
May 29 07:54:53 ser-pc bash[3694]: (EE) ############################################################################
May 29 07:54:53 ser-pc bash[3694]: (EE) SHELL_EXT: No compatible GNOME Shell extension responding via D-Bus.
May 29 07:54:53 ser-pc bash[3694]:         (Ignore this error if screen was locked/inactive at the time.)
May 29 07:54:53 ser-pc bash[3694]:         These shell extensions are compatible with keyszer:
May 29 07:54:53 ser-pc bash[3694]:             xremap@k0kubun.com (supports pre-GNOME 41.x):
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/5060/xremap/)
May 29 07:54:53 ser-pc bash[3694]:             window-calls-extended@hseliger.eu:
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/4974/window-calls-extended/)
May 29 07:54:53 ser-pc bash[3694]:             focused-window-dbus@flexagoon.com:
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/5592/focused-window-d-bus/)
May 29 07:54:53 ser-pc bash[3694]: (EE) Install "Extension Manager" from Flathub to manage GNOME Shell extensions
May 29 07:54:53 ser-pc bash[3694]: (EE) ############################################################################
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'xremap@k0kubun.com':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/com/k0kubun/Xremap”
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'window-calls-extended@hseliger.eu':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/org/gnome/Shell/Extensions/WindowsExt”
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'focused-window-dbus@flexagoon.com':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/org/gnome/shell/extensions/FocusedWindow”
May 29 07:54:53 ser-pc bash[3694]: (EE) ############################################################################
May 29 07:54:53 ser-pc bash[3694]: (EE) SHELL_EXT: No compatible GNOME Shell extension responding via D-Bus.
May 29 07:54:53 ser-pc bash[3694]:         (Ignore this error if screen was locked/inactive at the time.)
May 29 07:54:53 ser-pc bash[3694]:         These shell extensions are compatible with keyszer:
May 29 07:54:53 ser-pc bash[3694]:             xremap@k0kubun.com (supports pre-GNOME 41.x):
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/5060/xremap/)
May 29 07:54:53 ser-pc bash[3694]:             window-calls-extended@hseliger.eu:
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/4974/window-calls-extended/)
May 29 07:54:53 ser-pc bash[3694]:             focused-window-dbus@flexagoon.com:
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/5592/focused-window-d-bus/)
May 29 07:54:53 ser-pc bash[3694]: (EE) Install "Extension Manager" from Flathub to manage GNOME Shell extensions
May 29 07:54:53 ser-pc bash[3694]: (EE) ############################################################################
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'xremap@k0kubun.com':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/com/k0kubun/Xremap”
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'window-calls-extended@hseliger.eu':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/org/gnome/Shell/Extensions/WindowsExt”
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'focused-window-dbus@flexagoon.com':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/org/gnome/shell/extensions/FocusedWindow”
May 29 07:54:53 ser-pc bash[3694]: (EE) ############################################################################
May 29 07:54:53 ser-pc bash[3694]: (EE) SHELL_EXT: No compatible GNOME Shell extension responding via D-Bus.
May 29 07:54:53 ser-pc bash[3694]:         (Ignore this error if screen was locked/inactive at the time.)
May 29 07:54:53 ser-pc bash[3694]:         These shell extensions are compatible with keyszer:
May 29 07:54:53 ser-pc bash[3694]:             xremap@k0kubun.com (supports pre-GNOME 41.x):
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/5060/xremap/)
May 29 07:54:53 ser-pc bash[3694]:             window-calls-extended@hseliger.eu:
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/4974/window-calls-extended/)
May 29 07:54:53 ser-pc bash[3694]:             focused-window-dbus@flexagoon.com:
May 29 07:54:53 ser-pc bash[3694]:                 (https://extensions.gnome.org/extension/5592/focused-window-d-bus/)
May 29 07:54:53 ser-pc bash[3694]: (EE) Install "Extension Manager" from Flathub to manage GNOME Shell extensions
May 29 07:54:53 ser-pc bash[3694]: (EE) ############################################################################
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'xremap@k0kubun.com':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/com/k0kubun/Xremap”
May 29 07:54:53 ser-pc bash[3694]: (EE) D-Bus error querying GNOME Shell extension 'window-calls-extended@hseliger.eu':
May 29 07:54:53 ser-pc bash[3694]:         org.freedesktop.DBus.Error.UnknownMethod:
May 29 07:54:53 ser-pc bash[3694]:          Object does not exist at path “/org/gnome/Shell/Extensions/WindowsExt”

* * *

Problem observed:
Caps lock behavior is swapped after waking up from sleep. Caps on behaves like caps off and vice versa. Not a big deal though.

**Comment by RedBearAK** [comment] 2024-05-29 22:09
@amrit92 

Interesting. This can normally only happen inside a VM or some remote desktop app where you turn CapsLock on and then leave the app and hit CapsLock on the host without the guest or remote system knowing about it. I can't even imagine how this could happen outside that situation. Does this never happen with Toshy disabled? Does it happen in a specific app?

**Comment by SukkaW** [comment] 2024-06-01 10:33
@amrit92 @RedBearAK I am having the same behavior as well, but I don't believe this is the issue of Toshy. IMHO this is more likely an issue of GNOME. I am on Fedora 40 with GNOME 46, and I had this issue even before installing Toshy.

Here are others' reports:

- https://www.reddit.com/r/Fedora/comments/1bqqxpq/capslock_insanity_f40_beta/
- https://www.reddit.com/r/linuxquestions/comments/r8w6ar/caps_lock_reversed_in_linux/
- https://www.reddit.com/r/Fedora/comments/1bmntih/caps_lock_key_inverted/
- https://discussion.fedoraproject.org/t/why-sometimes-my-capslock-gets-inverted/109493
- https://discussion.fedoraproject.org/t/fedora-39-caps-lock-toggle-reversed-and-malfunctioning/95458
- https://gitlab.gnome.org/GNOME/mutter/-/issues/344

**Comment by RedBearAK** [comment] 2024-06-01 18:38
Thanks @SukkaW that makes a lot more sense than this somehow being caused by the keymapper behind Toshy. 

So @amrit92 I am going to close this as resolved since there is probably nothing Toshy can do about the issue. Even if you find that it happens more frequently or even very reliably while using Toshy, that would be something to add to the GNOME bug reports. The GNOME shell is the most likely culprit here.

**Closed by RedBearAK** 2024-06-01 18:38 UTC
Labels: bug
